// Real list of languages with an actual Hunspell dictionary available in the
// wooorm/dictionaries collection (verified against its repo listing - not
// every language has one; Hunspell-style affix dictionaries don't suit every
// script/morphology, so this list is intentionally smaller than a generic
// "every language" list would be). `code` matches both the GitHub directory
// name and the `dictionary-<code>` npm package name, which is also the path
// segment used to fetch the raw .aff/.dic files from jsDelivr at runtime.
export const SPELLCHECK_LANGUAGES = [
    { code: 'bg', name: 'Bulgarian' },
    { code: 'br', name: 'Breton' },
    { code: 'ca-valencia', name: 'Catalan (Valencian)' },
    { code: 'ca', name: 'Catalan' },
    { code: 'cs', name: 'Czech' },
    { code: 'cy', name: 'Welsh' },
    { code: 'da', name: 'Danish' },
    { code: 'de-AT', name: 'German (Austria)' },
    { code: 'de-CH', name: 'German (Switzerland)' },
    { code: 'de', name: 'German' },
    { code: 'el-polyton', name: 'Greek (Polytonic)' },
    { code: 'el', name: 'Greek' },
    { code: 'en-AU', name: 'English (Australia)' },
    { code: 'en-CA', name: 'English (Canada)' },
    { code: 'en-GB', name: 'English (UK)' },
    { code: 'en-ZA', name: 'English (South Africa)' },
    { code: 'en', name: 'English (US)' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'es-AR', name: 'Spanish (Argentina)' },
    { code: 'es-BO', name: 'Spanish (Bolivia)' },
    { code: 'es-CL', name: 'Spanish (Chile)' },
    { code: 'es-CO', name: 'Spanish (Colombia)' },
    { code: 'es-CR', name: 'Spanish (Costa Rica)' },
    { code: 'es-CU', name: 'Spanish (Cuba)' },
    { code: 'es-DO', name: 'Spanish (Dominican Republic)' },
    { code: 'es-EC', name: 'Spanish (Ecuador)' },
    { code: 'es-GT', name: 'Spanish (Guatemala)' },
    { code: 'es-HN', name: 'Spanish (Honduras)' },
    { code: 'es-MX', name: 'Spanish (Mexico)' },
    { code: 'es-NI', name: 'Spanish (Nicaragua)' },
    { code: 'es-PA', name: 'Spanish (Panama)' },
    { code: 'es-PE', name: 'Spanish (Peru)' },
    { code: 'es-PH', name: 'Spanish (Philippines)' },
    { code: 'es-PR', name: 'Spanish (Puerto Rico)' },
    { code: 'es-PY', name: 'Spanish (Paraguay)' },
    { code: 'es-SV', name: 'Spanish (El Salvador)' },
    { code: 'es-US', name: 'Spanish (US)' },
    { code: 'es-UY', name: 'Spanish (Uruguay)' },
    { code: 'es-VE', name: 'Spanish (Venezuela)' },
    { code: 'es', name: 'Spanish' },
    { code: 'et', name: 'Estonian' },
    { code: 'eu', name: 'Basque' },
    { code: 'fa', name: 'Persian' },
    { code: 'fo', name: 'Faroese' },
    { code: 'fr', name: 'French' },
    { code: 'fur', name: 'Friulian' },
    { code: 'fy', name: 'Western Frisian' },
    { code: 'ga', name: 'Irish' },
    { code: 'gd', name: 'Scottish Gaelic' },
    { code: 'gl', name: 'Galician' },
    { code: 'he', name: 'Hebrew' },
    { code: 'hr', name: 'Croatian' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'hy', name: 'Armenian' },
    { code: 'hyw', name: 'Western Armenian' },
    { code: 'ia', name: 'Interlingua' },
    { code: 'ie', name: 'Interlingue' },
    { code: 'is', name: 'Icelandic' },
    { code: 'it', name: 'Italian' },
    { code: 'ka', name: 'Georgian' },
    { code: 'ko', name: 'Korean' },
    { code: 'la', name: 'Latin' },
    { code: 'lb', name: 'Luxembourgish' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'ltg', name: 'Latgalian' },
    { code: 'lv', name: 'Latvian' },
    { code: 'mk', name: 'Macedonian' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'nb', name: 'Norwegian Bokmål' },
    { code: 'nds', name: 'Low German' },
    { code: 'ne', name: 'Nepali' },
    { code: 'nl', name: 'Dutch' },
    { code: 'nn', name: 'Norwegian Nynorsk' },
    { code: 'oc', name: 'Occitan' },
    { code: 'pl', name: 'Polish' },
    { code: 'pt-PT', name: 'Portuguese (Portugal)' },
    { code: 'pt', name: 'Portuguese (Brazil)' },
    { code: 'ro', name: 'Romanian' },
    { code: 'ru', name: 'Russian' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'sr-Latn', name: 'Serbian (Latin)' },
    { code: 'sr', name: 'Serbian' },
    { code: 'sv-FI', name: 'Swedish (Finland)' },
    { code: 'sv', name: 'Swedish' },
    { code: 'tk', name: 'Turkmen' },
    { code: 'tlh-Latn', name: 'Klingon (Latin)' },
    { code: 'tlh', name: 'Klingon' },
    { code: 'tr', name: 'Turkish' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'vi', name: 'Vietnamese' },
].sort((a, b) => a.name.localeCompare(b.name));
