import { useEffect, useState } from 'react';
const SUPPORTED = typeof window !== 'undefined' && 'speechSynthesis' in window;
export default function TextToSpeechPreview() {
  const [text, setText] = useState('Type something and press Speak to hear it read aloud.');
  const [voices, setVoices] = useState([]);
  const [voiceURI, setVoiceURI] = useState('');
  const [rate, setRate] = useState(1);
  const [pitch, setPitch] = useState(1);
  const [speaking, setSpeaking] = useState(false);
  useEffect(() => {
    if (!SUPPORTED) return;
    function loadVoices() {
      const list = window.speechSynthesis.getVoices();
      setVoices(list);
      setVoiceURI((prev) => prev || list[0]?.voiceURI || '');
    }
    loadVoices();
    window.speechSynthesis.addEventListener('voiceschanged', loadVoices);
    return () => {
      window.speechSynthesis.removeEventListener('voiceschanged', loadVoices);
      window.speechSynthesis.cancel();
    };
  }, []);
  function handleSpeak() {
    if (!SUPPORTED || !text) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    const voice = voices.find((v) => v.voiceURI === voiceURI);
    if (voice) utterance.voice = voice;
    utterance.rate = rate;
    utterance.pitch = pitch;
    utterance.onend = () => setSpeaking(false);
    utterance.onerror = () => setSpeaking(false);
    setSpeaking(true);
    window.speechSynthesis.speak(utterance);
  }
  function handleStop() {
    if (!SUPPORTED) return;
    window.speechSynthesis.cancel();
    setSpeaking(false);
  }
  return (
    <div className="tool-page">
      <h1>Text-to-Speech Preview</h1>
      <p className="tool-description">
        Type or paste text and hear it read aloud using your browser's built-in speech synthesis,
        with a choice of installed voices plus rate and pitch controls. Uses the browser's
        built-in speech engine - no audio is uploaded or generated by a server.
      </p>
      {!SUPPORTED && (
        <div className="tool-error">
          Your browser does not support the Web Speech API (speechSynthesis). Try a recent version
          of Chrome, Edge, or Safari.
        </div>
      )}
      <div className="tool-controls">
        <label>
          Voice:
          <select value={voiceURI} onChange={(e) => setVoiceURI(e.target.value)} disabled={!SUPPORTED || voices.length === 0}>
            {voices.length === 0 && <option value="">No voices available</option>}
            {voices.map((v) => (
              <option key={v.voiceURI} value={v.voiceURI}>
                {v.name} ({v.lang})
              </option>
            ))}
          </select>
        </label>
        <label>
          Rate: {rate.toFixed(1)}
          <input
            type="range"
            min={0.5}
            max={2}
            step={0.1}
            value={rate}
            onChange={(e) => setRate(Number(e.target.value))}
            disabled={!SUPPORTED}
          />
        </label>
        <label>
          Pitch: {pitch.toFixed(1)}
          <input
            type="range"
            min={0}
            max={2}
            step={0.1}
            value={pitch}
            onChange={(e) => setPitch(Number(e.target.value))}
            disabled={!SUPPORTED}
          />
        </label>
        <button onClick={handleSpeak} disabled={!SUPPORTED || !text}>
          {speaking ? 'Speaking...' : 'Speak'}
        </button>
        <button onClick={handleStop} disabled={!SUPPORTED || !speaking}>
          Stop
        </button>
      </div>
      <div className="tool-panel">
        <label htmlFor="tts-input">Text</label>
        <textarea
          id="tts-input"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Type something to speak"
          style={{ minHeight: 180 }}
        />
      </div>
    </div>
  );
}
